<?php
/**
 * Quick Email Setup Helper
 * This file helps you quickly configure email for OTP sending
 * Access: http://localhost/vaxforsure/QUICK_EMAIL_SETUP.php
 */

require_once 'config.php';

// Auto-install PHPMailer if not present
$phpmailerPath = __DIR__ . '/PHPMailer/src/PHPMailer.php';
if (!file_exists($phpmailerPath)) {
    // Try to install PHPMailer automatically
    $phpmailerDir = __DIR__ . '/PHPMailer/src';
    if (!is_dir($phpmailerDir)) {
        mkdir($phpmailerDir, 0755, true);
    }
    
    $files = [
        'PHPMailer.php' => 'https://raw.githubusercontent.com/PHPMailer/PHPMailer/master/src/PHPMailer.php',
        'SMTP.php' => 'https://raw.githubusercontent.com/PHPMailer/PHPMailer/master/src/SMTP.php',
        'Exception.php' => 'https://raw.githubusercontent.com/PHPMailer/PHPMailer/master/src/Exception.php'
    ];
    
    foreach ($files as $filename => $url) {
        $filepath = $phpmailerDir . '/' . $filename;
        if (!file_exists($filepath)) {
            $content = @file_get_contents($url, false, stream_context_create([
                'http' => ['timeout' => 10, 'user_agent' => 'PHP']
            ]));
            if ($content && strlen($content) > 100) {
                file_put_contents($filepath, $content);
            }
        }
    }
}

header('Content-Type: text/html; charset=UTF-8');

echo "<!DOCTYPE html><html><head><title>Quick Email Setup</title>";
echo "<style>
body{font-family:Arial;padding:20px;background:#f5f5f5;max-width:900px;margin:0 auto;}
.success{color:green;padding:15px;background:#d4edda;border:2px solid #4caf50;margin:10px 0;border-radius:5px;}
.error{color:red;padding:15px;background:#f8d7da;border:2px solid #f44336;margin:10px 0;border-radius:5px;}
.info{color:#0c5460;padding:15px;background:#d1ecf1;border:2px solid #2196f3;margin:10px 0;border-radius:5px;}
.warning{color:#856404;padding:15px;background:#fff3cd;border:2px solid #ff9800;margin:10px 0;border-radius:5px;}
h1{color:#333;border-bottom:3px solid #4DB6AC;padding-bottom:10px;}
h2{color:#555;margin-top:30px;}
input,textarea{width:100%;padding:10px;margin:5px 0;border:1px solid #ddd;border-radius:5px;box-sizing:border-box;font-size:14px;}
button{background:#4DB6AC;color:white;padding:12px 24px;border:none;border-radius:5px;cursor:pointer;font-size:16px;margin:5px;}
button:hover{background:#00897B;}
.code-block{background:#f4f4f4;padding:15px;border-radius:5px;overflow-x:auto;font-family:monospace;font-size:12px;margin:10px 0;}
.step{background:white;padding:20px;margin:15px 0;border-radius:5px;border-left:4px solid #4DB6AC;}
</style></head><body>";

echo "<h1>⚡ Quick Email Setup for VaxForSure</h1>";

$configFile = __DIR__ . '/email_config.php';
$templateFile = __DIR__ . '/email_config.php.template';

// Handle form submission
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['save_config'])) {
    $smtp_host = $_POST['smtp_host'] ?? 'smtp.gmail.com';
    $smtp_port = $_POST['smtp_port'] ?? '587';
    $smtp_username = $_POST['smtp_username'] ?? '';
    $smtp_password = $_POST['smtp_password'] ?? '';
    $smtp_from_email = $_POST['smtp_from_email'] ?? '';
    $smtp_from_name = $_POST['smtp_from_name'] ?? 'VaxForSure';
    
    if (empty($smtp_username) || empty($smtp_password)) {
        echo "<div class='error'><strong>❌ Error:</strong> Email and password are required!</div>";
    } else {
        $configContent = "<?php\n";
        $configContent .= "/**\n";
        $configContent .= " * Email Configuration\n";
        $configContent .= " * Auto-generated by QUICK_EMAIL_SETUP.php\n";
        $configContent .= " */\n\n";
        $configContent .= "\$smtp_host = '" . addslashes($smtp_host) . "';\n";
        $configContent .= "\$smtp_port = " . intval($smtp_port) . ";\n";
        $configContent .= "\$smtp_username = '" . addslashes($smtp_username) . "';\n";
        $configContent .= "\$smtp_password = '" . addslashes($smtp_password) . "';\n";
        $configContent .= "\$smtp_from_email = '" . addslashes($smtp_from_email) . "';\n";
        $configContent .= "\$smtp_from_name = '" . addslashes($smtp_from_name) . "';\n";
        $configContent .= "\n?>\n";
        
        if (file_put_contents($configFile, $configContent)) {
            echo "<div class='success'><strong>✅ Configuration saved successfully!</strong><br>";
            echo "Email configuration has been saved to: <code>email_config.php</code></div>";
            
            // Test email if test email provided
            if (!empty($_POST['test_email'])) {
                $testEmail = $_POST['test_email'];
                $testOtp = generateOTP();
                
                $subject = "Test Email - VaxForSure";
                $message = "
                <html>
                <body style='font-family:Arial;padding:20px;'>
                    <h2 style='color:#4DB6AC;'>VaxForSure - Test Email</h2>
                    <p>This is a test email to verify your email configuration.</p>
                    <div style='background:#f0f0f0;padding:20px;margin:20px 0;border-radius:5px;text-align:center;'>
                        <h3>Test OTP Code:</h3>
                        <div style='font-size:32px;font-weight:bold;color:#4DB6AC;letter-spacing:5px;'>$testOtp</div>
                    </div>
                    <p>If you received this email, your email configuration is working correctly!</p>
                </body>
                </html>
                ";
                
                echo "<div class='info'><strong>📧 Sending test email...</strong></div>";
                $result = sendEmail($testEmail, $subject, $message);
                
                if ($result) {
                    echo "<div class='success'><strong>✅ Test email sent successfully!</strong><br>";
                    echo "Please check your inbox at: <strong>$testEmail</strong><br>";
                    echo "Also check your spam/junk folder if you don't see it.</div>";
                } else {
                    echo "<div class='warning'><strong>⚠️ Test email sending failed.</strong><br>";
                    echo "This might be due to:<br>";
                    echo "1. Incorrect email credentials<br>";
                    echo "2. Gmail security settings blocking the connection<br>";
                    echo "3. Firewall blocking port 587<br><br>";
                    echo "Please verify your credentials and try again.</div>";
                }
            }
        } else {
            echo "<div class='error'><strong>❌ Error:</strong> Failed to save configuration file. Please check file permissions.</div>";
        }
    }
    echo "<hr>";
}

// Check if config exists
$configExists = file_exists($configFile);
$currentConfig = [];
if ($configExists) {
    include $configFile;
    $currentConfig = [
        'host' => $smtp_host ?? 'smtp.gmail.com',
        'port' => $smtp_port ?? '587',
        'username' => $smtp_username ?? '',
        'from_email' => $smtp_from_email ?? '',
        'from_name' => $smtp_from_name ?? 'VaxForSure'
    ];
}

?>

<div class="info">
    <h2>📋 Setup Instructions</h2>
    
    <div class="step">
        <h3>Step 1: Get Gmail App Password</h3>
        <ol>
            <li>Go to: <a href="https://myaccount.google.com/" target="_blank">Google Account Settings</a></li>
            <li>Click <strong>"Security"</strong> on the left sidebar</li>
            <li>Enable <strong>"2-Step Verification"</strong> (if not already enabled)</li>
            <li>Go back to Security → Scroll down to <strong>"App passwords"</strong></li>
            <li>Select app: <strong>"Mail"</strong> and device: <strong>"Other (Custom name)"</strong></li>
            <li>Enter name: <strong>"VaxForSure"</strong></li>
            <li>Click <strong>"Generate"</strong></li>
            <li><strong>Copy the 16-character password</strong> (you'll need this below)</li>
        </ol>
        <p><strong>Important:</strong> Use App Password, NOT your regular Gmail password!</p>
    </div>
    
    <div class="step">
        <h3>Step 2: Enter Your Email Credentials</h3>
        <p>Fill in the form below with your Gmail address and App Password.</p>
    </div>
    
    <div class="step">
        <h3>Step 3: Test Email Sending</h3>
        <p>After saving, enter your email address to receive a test email. If you receive it, you're all set!</p>
    </div>
</div>

<hr>

<h2>⚙️ Email Configuration</h2>

<?php if ($configExists): ?>
<div class="success">
    <strong>✅ Configuration file exists!</strong> You can update it below or test it using the form.
</div>
<?php else: ?>
<div class="warning">
    <strong>⚠️ No configuration file found.</strong> Please fill in the form below to create one.
</div>
<?php endif; ?>

<form method="POST">
    <label><strong>SMTP Host:</strong></label>
    <input type="text" name="smtp_host" value="<?php echo htmlspecialchars($currentConfig['host'] ?? 'smtp.gmail.com'); ?>" required>
    
    <label><strong>SMTP Port:</strong></label>
    <input type="number" name="smtp_port" value="<?php echo htmlspecialchars($currentConfig['port'] ?? '587'); ?>" required>
    <small>Use 587 for TLS or 465 for SSL</small>
    
    <label><strong>Your Gmail Address:</strong></label>
    <input type="email" name="smtp_username" value="<?php echo htmlspecialchars($currentConfig['username'] ?? ''); ?>" placeholder="your-email@gmail.com" required>
    
    <label><strong>Gmail App Password:</strong></label>
    <input type="password" name="smtp_password" placeholder="Enter 16-character App Password" required>
    <small>This is the App Password from Step 1, NOT your regular password</small>
    
    <label><strong>From Email:</strong></label>
    <input type="email" name="smtp_from_email" value="<?php echo htmlspecialchars($currentConfig['from_email'] ?? ''); ?>" placeholder="your-email@gmail.com" required>
    <small>Usually the same as your Gmail address</small>
    
    <label><strong>From Name:</strong></label>
    <input type="text" name="smtp_from_name" value="<?php echo htmlspecialchars($currentConfig['from_name'] ?? 'VaxForSure'); ?>" required>
    
    <hr>
    
    <h3>🧪 Test Email (Optional)</h3>
    <p>Enter your email address to receive a test email after saving configuration:</p>
    <label><strong>Test Email Address:</strong></label>
    <input type="email" name="test_email" placeholder="test@example.com">
    <small>Leave empty if you don't want to test now</small>
    
    <br><br>
    <button type="submit" name="save_config">💾 Save Configuration</button>
    <a href="CONFIGURE_EMAIL.php"><button type="button">🧪 Go to Email Tester</button></a>
</form>

<hr>

<h2>📝 Current Status</h2>
<div class="info">
    <?php if ($configExists): ?>
        <p><strong>Configuration File:</strong> <code>email_config.php</code> ✅ Exists</p>
        <p><strong>SMTP Host:</strong> <?php echo htmlspecialchars($currentConfig['host'] ?? 'Not set'); ?></p>
        <p><strong>SMTP Port:</strong> <?php echo htmlspecialchars($currentConfig['port'] ?? 'Not set'); ?></p>
        <p><strong>Email:</strong> <?php echo htmlspecialchars($currentConfig['username'] ?? 'Not set'); ?></p>
        <p><strong>From Name:</strong> <?php echo htmlspecialchars($currentConfig['from_name'] ?? 'Not set'); ?></p>
    <?php else: ?>
        <p><strong>Configuration File:</strong> <code>email_config.php</code> ❌ Not found</p>
        <p>Please fill in the form above to create the configuration file.</p>
    <?php endif; ?>
</div>

<hr>

<h2>✅ Next Steps</h2>
<div class="step">
    <ol>
        <li>✅ Save your email configuration using the form above</li>
        <li>✅ Test email sending</li>
        <li>✅ Try forgot password from your app</li>
        <li>✅ Check your email inbox for the OTP code</li>
    </ol>
</div>

</body></html>

